### ISSUE TITLE
The package is broken

### ISSUE THREAD

**Issue by denisk20** [kestrelm/Creature_LibGDX#1]
Please consider putting all files into appropriate package for the ease of usage. Better yet, please consider putting the sources into a libgdx gradle project with a simple example.

**Comment by denisk20** [comment]
I have created a test project, but it currently throws an error (see issue 1):
https://github.com/denisk20/libgdx-creature-example

**Comment by kestrelm** [comment]
Hello,
I just checked in the fix, moved the files into the correct folder for import and updated the posing code. The new posing code is a lot faster (uses the same algorithm as the ones in the UE4 and Unity runtimes)
