### ISSUE TITLE
Android OutOfMemoryError

### ISSUE THREAD

**Issue by denisk20** [kestrelm/Creature_LibGDX#3]
When running test project from https://github.com/denisk20/libgdx-creature-example on Android device I'm getting an error:

```
10-22 12:19:52.629 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 48-byte allocation.
10-22 12:19:54.066 18941-18948/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 48-byte allocation.
10-22 12:19:55.518 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 112-byte allocation.
10-22 12:19:56.976 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 78-byte allocation.
10-22 12:19:58.405 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 112-byte allocation.
10-22 12:19:59.830 18941-18948/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 64-byte allocation.
10-22 12:20:01.286 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 68-byte allocation.
10-22 12:20:02.735 18941-18948/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 48-byte allocation.
10-22 12:20:04.766 18941-18962/com.gdxcreature.android E/dalvikvm-heap: Out of memory on a 112-byte allocation.
10-22 12:20:05.822 18941-18962/com.gdxcreature.android E/AndroidRuntime: FATAL EXCEPTION: GLThread 4266
10-22 12:20:05.822 18941-18962/com.gdxcreature.android E/AndroidRuntime: java.lang.OutOfMemoryError: [memory exhausted]
10-22 12:20:05.822 18941-18962/com.gdxcreature.android E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kestrelm** [comment]
Hello,
Please check the new updates on the forum here:
http://www.kestrelmoon.com/creatureforum/viewtopic.php?f=3&t=204&start=10

Essentially I just checked in the ability to read in the new fast flat binary data format. You will need to grab the converter from the Creature_Tools page as well. The new binary reader does not allocate a DOM tree but just reads off the Flat Data API so hopefully it will help in terms of load time memory performance.

**Comment by kestrelm** [comment]
Hello,

I just updated the package with a new file that should now convert correctly on both Mac and Windows.
Please re-download here:
http://creature.kestrelmoon.com/Ue4_export.zip
The binary file with a .bin extension has also been packaged up with it for convenience.

**Comment by kestrelm** [comment]
Hello,

Just packaged it up for LibGDX and checked it in:
https://github.com/kestrelm/Creature_LibGDX

Please let me know if there are any issues. I have also included the json and bin files with the package.

Cheers

**Comment by denisk20** [comment]
Trying to run on Android with new binary importer...

**Comment by kestrelm** [comment]
Sync up again, I just added precision modifiers...
Now it should hopefully detect that you are on an OpenGL ES platform and put in the precision modifiers required by OpenGL ES.

Check out the new file:
https://github.com/kestrelm/Creature_LibGDX/blob/master/desktop/MeshBoneShader.frag

I am using the official LibGDX docs as reference:
https://github.com/libgdx/libgdx/wiki/Opengl-es-support

**Comment by kestrelm** [comment]
Hello,

I just did another slight update.
Please examine the 2 shader files.

Vertex Shader:
https://github.com/kestrelm/Creature_LibGDX/blob/master/desktop/MeshBoneShader.vert

Fragment Shader:
https://github.com/kestrelm/Creature_LibGDX/blob/master/desktop/MeshBoneShader.frag

The error you were encountering was most probably because the shaders did not compile on an OpenGL ES platform since the syntax is different from regular desktop GLSL.

The process to make shaders cross platform is documented here:
http://www.gamefromscratch.com/post/2014/07/08/LibGDX-Tutorial-Part-12-Using-GLSL-Shaders-and-creating-a-Mesh.aspx

Notice that I am now having ifdefs in the fragment shader to make it compile through. It looks like the ifdefs are not needed in the vertex shader case.

Let me know if it runs for you.

Cheers,
Chong

**Comment by denisk20** [comment]
It runs now! I have incorporated these changes to create a fully-functional android demo, created a pull request for it. Thanks!

**Comment by denisk20** [comment]
And thanks for the link, that article is really interesting.

**Comment by kestrelm** [comment]
No problem! I am glad it all worked out. Also, I am very happy the binary loader is now in the LibGDX runtime, it has improved the runtime greatly!

Cheers!
