### ISSUE TITLE
Many allocations occur on each frame

### ISSUE THREAD

**Issue by denisk20** [kestrelm/Creature_LibGDX#6]
It seems that Quaternions are created on each frame draw causing garbage collector execute often. This is likely the source of frame drops.
![image](https://cloud.githubusercontent.com/assets/3080318/10708944/37119b6e-7a24-11e5-95db-9c73be848171.png)
Let me see if it's an easy fix, if so I'll provide a pull request.

**Comment by kestrelm** [comment]
The overhead in poseFinalPts() might be due to the fact that a couple of Vector3s are getting allocated in the loop. I think by just allocating them outside of the main loop and setting values within quite a few allocations can be saved. This is probably easier to implement first than porting over point caching.

**Comment by kestrelm** [comment]
You can sync up again... I just made some changes that removes quite a few new allocations in the inner loop of poseFinalPts. It should do almost no new allocations during poseFinalPts during the inner loop now. Can you profile it and see how it goes?

**Comment by denisk20** [comment]
It looks a bit better, but still there are some major performance offenders:
![image](https://cloud.githubusercontent.com/assets/3080318/10711881/eaa2beac-7a91-11e5-9549-afc40d09f0b6.png)
Most noticeable ones are:
- MeshBoneUtil.MeshBone#computeWorldDeltaTransforms: `world_dq = new dualQuat(cur_quat, tmp_pos);`
- MeshBoneUtil.MeshBoneCacheManager#retrieveValuesAtTime: new vectors inside the loop created with `cpy()`
- MeshBoneUtil.MeshRenderRegion#poseFinalPts: `accum_dq.add` uses `cpy()` internally to spawn new vectors

**Comment by kestrelm** [comment]
Point Caching has been ported over to the java runtimes. It should be much faster now with it enabled.
Look at: https://github.com/kestrelm/Creature_LibGDX/blob/master/core/src/com/mygdx/game/MyGdxGame.java

To see an example of how to switch it on. Essentially, after adding the animation to the CreatureManager, you do:

 new_creature_manager.MakePointCache("default", 2); 
First argument is name of animation to generate point cache on.
Second argument is the gap. The default is 1 which means you generate a cache for every time sample. This is the most accurate but also most memory intensive. For the raptor, you can probably go all the way up to a gap of 5 without much quality loss. Having a larger gap reduces memory requirements but also results in loss of detail. You can play around with it, I think 2 - 5 are good values to try.

The point caching skips the posing engine altogether which means it should be better for the GC, has less computation and should speed up playback performance.

**Comment by denisk20** [comment]
That's awesome, great work! It now runs like a rocket! I have noticed that one small performance abuser was still there, I have submitted a pull request to fix it.

**Comment by kestrelm** [comment]
Sounds great! Thanks for the confirmation about the performance speedup on your end! Hope to see you using Creature soon!

Cheers!

**Comment by denisk20** [comment]
Absolutely! Now as it's libgdx-ready it should be much easier decision to make.
